version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: hexagonal_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: spring_hexagonal
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
